import { generateUid } from './generate-uid.helper';
import { getAutoGeneratedLegends } from './get-auto-generated-legend-sets.helper';
import { LegendSet } from '../models';

export function getAutoGeneratedLegendSet(legendSetName?: string): LegendSet {
  return {
    id: generateUid(),
    name: legendSetName || 'Default',
    legends: getAutoGeneratedLegends()
  };
}
