export enum AuthoritiesEnums {
  BNA_ADD_INTERVENTION = "BNA_ADD_INTERVENTION",
  BNA_EDIT_INTERVENTION = "BNA_EDIT_INTERVENTION",
  BNA_DELETE_INTERVENTION = "BNA_DELETE_INTERVENTION",
  BNA_VIEW_INTERVENTIONS = "BNA_VIEW_INTERVENTIONS",
  BNA_ADD_ROOT_CAUSE = "BNA_ADD_ROOT_CAUSE",
  BNA_EDIT_ROOT_CAUSE = "BNA_EDIT_ROOT_CAUSE",
  BNA_DELETE_ROOT_CAUSE = "BNA_DELETE_ROOT_CAUSE",
  BNA_DELETE_ARCHIVE = "BNA_DELETE_ARCHIVE",
  BNA_ADD_ARCHIVE = "BNA_ADD_ARCHIVE",
}
