import { getDashboardAccess } from './get-dashboard-access.helper';
import { User } from '@iapps/ngx-dhis2-http-client';

const dashboard = {
  id: 'Xg8L14BRydy',
  name: 'ARVs for PMTCT',
  user: {
    id: 'M5zQapPyTZI',
    name: 'admin admin',
  },
  publicAccess: '--------',
  userAccesses: [
    {
      id: 'YXz40ijLGJr',
      name: 'Bottleneck User',
      type: 'user',
      access: 'r-------',
    },
  ],
  externalAccess: false,
  userGroupAccesses: [
    {
      id: 'GCI348yKvGT',
      name: 'Cause of death admin',
      type: 'userGroup',
      access: '--------',
    },
    {
      id: 'KrlFAbMi6JI',
      name: 'Program Managers',
      type: 'userGroup',
      access: 'r-------',
    },
    {
      id: 'lFSq9HYuNoA',
      name: 'Dashboard Admin',
      type: 'userGroup',
      access: 'rw------',
      displayName: 'Dashboard Admin',
    },
  ],
};

describe('Given a dashboard and user who created the dashboard', () => {
  const user: User = {
    lastUpdated: '2020-04-20T11:52:33.684',
    created: '2018-12-03T11:25:51.014',
    name: 'admin admin',
    id: 'M5zQapPyTZI',
    displayName: 'admin admin',
    email: 'admin@dhis2.org',
    userCredentials: {
      username: 'admin',
    },
    userGroups: [],
    organisationUnits: [{ level: 1, name: 'Trainingland', id: 'GD7TowwI46c' }],
    dataViewOrganisationUnits: [
      { level: 1, name: 'Trainingland', id: 'GD7TowwI46c' },
    ],
    authorities: [
      'F_PROGRAM_INDICATOR_PUBLIC_ADD',
      'F_SQLVIEW_EXECUTE',
      'F_USER_VIEW',
      'F_GENERATE_MIN_MAX_VALUES',
      'F_VALIDATIONRULE_PUBLIC_ADD',
      'F_CATEGORY_PRIVATE_ADD',
      'F_INDICATORGROUPSET_PUBLIC_ADD',
      'F_DATAVALUE_DELETE',
      'F_EXTERNAL_MAP_LAYER_PRIVATE_ADD',
      'F_RELATIONSHIPTYPE_DELETE',
      'F_REPORTTABLE_EXTERNAL',
      'F_CATEGORY_OPTION_PRIVATE_ADD',
      'F_GIS_ADMIN',
      'F_CATEGORY_OPTION_GROUP_PUBLIC_ADD',
      'M_dhis-web-event-capture',
      'F_SEND_EMAIL',
      'F_ORGUNITGROUPSET_PRIVATE_ADD',
      'F_INDICATOR_DELETE',
      'M_dhis-web-event-reports',
      'F_VIEW_UNAPPROVED_DATA',
      'F_USERGROUP_MANAGING_RELATIONSHIPS_VIEW',
      'F_OPTIONGROUPSET_DELETE',
      'F_USERGROUP_PUBLIC_ADD',
      'F_PROGRAM_INDICATOR_GROUP_PRIVATE_ADD',
      'F_TRACKED_ENTITY_ATTRIBUTE_PUBLIC_ADD',
      'F_PROGRAM_INDICATOR_DELETE',
      'F_TRACKED_ENTITY_ADD',
      'F_VALIDATIONRULEGROUP_PUBLIC_ADD',
      'F_DOCUMENT_PRIVATE_ADD',
      'F_TRACKED_ENTITY_DELETE',
      'M_Bottleneck_Analysis_App',
      'F_PROGRAM_PRIVATE_ADD',
      'F_REPORTTABLE_PUBLIC_ADD',
      'F_CATEGORY_COMBO_PRIVATE_ADD',
      'BNA_ADD_INTERVENTION',
      'F_PROGRAM_INDICATOR_GROUP_DELETE',
      'F_ORGANISATIONUNIT_MOVE',
      'F_EXTERNAL_MAP_LAYER_PUBLIC_ADD',
      'M_dhis-web-usage-analytics',
      'F_INDICATORGROUP_DELETE',
      'F_ORGANISATIONUNIT_DELETE',
      'F_PROGRAM_RULE_ADD',
      'F_OPTIONGROUPSET_PRIVATE_ADD',
      'M_BNA_Dashboard_Mock_up_2',
      'F_CATEGORY_COMBO_DELETE',
      'F_SECTION_DELETE',
      'F_USER_DELETE',
      'F_INDICATORGROUPSET_PRIVATE_ADD',
      'F_PROGRAM_INDICATOR_PRIVATE_ADD',
      'F_METADATA_IMPORT',
      'F_EXPORT_EVENTS',
      'F_SQLVIEW_PUBLIC_ADD',
      'M_i18n_Utility_App',
      'F_PERFORM_MAINTENANCE',
      'F_COLOR_SET_ADD',
      'F_MINMAX_DATAELEMENT_ADD',
      'F_METADATA_EXPORT',
      'F_PROGRAMSTAGE_SECTION_ADD',
      'F_DATAELEMENTGROUP_PRIVATE_ADD',
      'F_VALIDATIONRULE_PRIVATE_ADD',
      'F_APPROVE_DATA',
      'M_dhis-web-mapping',
      'F_DATAELEMENT_PRIVATE_ADD',
      'F_VALIDATIONCRITERIA_ADD',
      'F_TRACKED_ENTITY_INSTANCE_SEARCH_IN_ALL_ORGUNITS',
      'F_IGNORE_TRACKER_REQUIRED_VALUE_VALIDATION',
      'F_PROGRAM_PUBLIC_ADD',
      'F_CATEGORY_OPTION_GROUP_SET_PRIVATE_ADD',
      'F_CATEGORY_OPTION_GROUP_SET_DELETE',
      'M_Bottleneck_Analysis_App_TEST_FOR_DEMO',
      'F_USER_ADD_WITHIN_MANAGED_GROUP',
      'F_ORGANISATIONUNIT_ADD',
      'F_LEGEND_SET_PUBLIC_ADD',
      'F_CONSTANT_ADD',
      'M_Action_Tracker',
      'M_dhis-web-visualizer',
      'F_INDICATORGROUP_PUBLIC_ADD',
      'F_INDICATOR_PUBLIC_ADD',
      'M_Interactive_Dashboard_2__Beta_12',
      'F_TRACKED_ENTITY_ATTRIBUTE_PRIVATE_ADD',
      'M_WHO_Data_Quality_Tool',
      'F_TEI_CASCADE_DELETE',
      'F_FRED_UPDATE',
      'M_dhis-web-cache-cleaner',
      'F_EDIT_EXPIRED',
      'F_PROGRAM_DASHBOARD_CONFIG_ADMIN',
      'F_ORGANISATIONUNITLEVEL_UPDATE',
      'F_CATEGORY_OPTION_PUBLIC_ADD',
      'F_CATEGORY_OPTION_DELETE',
      'M_dhis-web-menu-management',
      'F_REPORT_PUBLIC_ADD',
      'F_VALIDATIONRULEGROUP_DELETE',
      'F_PROGRAM_TRACKED_ENTITY_ATTRIBUTE_GROUP_ADD',
      'M_Score_Card_Widget',
      'F_OPTIONSET_PRIVATE_ADD',
      'F_PROGRAM_RULE_DELETE',
      'F_ORGUNITGROUP_DELETE',
      'F_DATAELEMENTGROUPSET_PRIVATE_ADD',
      'F_LOCALE_ADD',
      'F_LEGEND_ADD',
      'F_CATEGORY_OPTION_GROUP_PRIVATE_ADD',
      'M_Immunisation_analysis',
      'M_Bottleneck_Analysis_App_TEST',
      'M_dhis-web-reporting',
      'F_SECTION_ADD',
      'F_CATEGORY_PUBLIC_ADD',
      'F_CATEGORY_COMBO_PUBLIC_ADD',
      'F_DATASET_DELETE',
      'F_INDICATORGROUPSET_DELETE',
      'F_ADD_TRACKED_ENTITY_FORM',
      'F_OPTIONGROUP_PUBLIC_ADD',
      'M_WHO_Malaria_Dashboard',
      'F_USERROLE_PRIVATE_ADD',
      'M_dhis-web-messaging',
      'M_dhis-web-maintenance-program',
      'F_EXTERNALFILERESOURCE_ADD',
      'M_bna_widget',
      'F_MAP_EXTERNAL',
      'F_DATAELEMENTGROUP_DELETE',
      'F_DATAELEMENTGROUPSET_PUBLIC_ADD',
      'F_USERGROUP_MANAGING_RELATIONSHIPS_ADD',
      'F_ORGUNITGROUP_PRIVATE_ADD',
      'F_DATAELEMENTGROUP_PUBLIC_ADD',
      'F_USER_GROUPS_READ_ONLY_ADD_MEMBERS',
      'F_LOCALE_DELETE',
      'F_PREDICTOR_RUN',
      'F_DATAELEMENT_DELETE',
      'F_OPTIONGROUP_DELETE',
      'F_LEGEND_SET_PRIVATE_ADD',
      'F_PROGRAMSTAGE_DELETE',
      'F_ATTRIBUTE_PUBLIC_ADD',
      'F_TRACKED_ENTITY_FORM_DELETE',
      'F_USERROLE_DELETE',
      'F_DOCUMENT_DELETE',
      'F_ORGUNITGROUPSET_DELETE',
      'M_dhis-web-translations',
      'F_PROGRAM_DELETE',
      'F_VALIDATIONRULE_DELETE',
      'F_RELATIONSHIPTYPE_PUBLIC_ADD',
      'F_PREDICTOR_ADD',
      'F_SQLVIEW_PRIVATE_ADD',
      'F_EXPORT_DATA',
      'M_WHO_Metadata_browser',
      'F_OAUTH2_CLIENT_MANAGE',
      'F_ORGUNITGROUP_PUBLIC_ADD',
      'F_APPROVE_DATA_LOWER_LEVELS',
      'F_OPTIONSET_PUBLIC_ADD',
      'M_dhis-web-dataentry',
      'F_USERROLE_PUBLIC_ADD',
      'F_ORGUNITGROUPSET_PUBLIC_ADD',
      'F_SQLVIEW_EXTERNAL',
      'F_REPORT_DELETE',
      'F_CONSTANT_DELETE',
      'F_DASHBOARD_PUBLIC_ADD',
      'F_PREDICTOR_DELETE',
      'F_CHART_PUBLIC_ADD',
      'M_dhis-web-data-visualizer',
      'F_CHART_EXTERNAL',
      'F_DATASET_PRIVATE_ADD',
      'M_Bottleneck_Analysis_App_TESTFORDEMO',
      'F_PROGRAMSTAGE_SECTION_DELETE',
      'M_Scorecard',
      'F_CATEGORY_OPTION_GROUP_SET_PUBLIC_ADD',
      'F_METADATA_MANAGE',
      'F_UNCOMPLETE_EVENT',
      'ALL',
      'F_LEGEND_DELETE',
      'F_MAP_PUBLIC_ADD',
      'F_DATAELEMENT_MINMAX_DELETE',
      'F_REPORT_PRIVATE_ADD',
      'F_VALIDATIONRULEGROUP_PRIVATE_ADD',
      'F_PUSH_ANALYSIS_DELETE',
      'F_REPLICATE_USER',
      'F_DATAVALUE_ADD',
      'F_INSERT_CUSTOM_JS_CSS',
      'F_DATAELEMENTGROUPSET_DELETE',
      'F_SQLVIEW_DELETE',
      'F_ENROLLMENT_CASCADE_DELETE',
      'F_INDICATORTYPE_ADD',
      'F_LEGEND_SET_DELETE',
      'F_VIEW_EVENT_ANALYTICS',
      'F_IMPORT_EVENTS',
      'F_INDICATOR_PRIVATE_ADD',
      'F_FRED_CREATE',
      'F_PUSH_ANALYSIS_ADD',
      'M_dhis-web-event-visualizer',
      'F_EXTERNAL_MAP_LAYER_DELETE',
      'F_ATTRIBUTE_PRIVATE_ADD',
      'F_TRACKED_ENTITY_ATTRIBUTE_DELETE',
      'F_DATAELEMENT_MINMAX_ADD',
      'M_dhis-web-data-quality',
      'M_dhis-web-pivot',
      'F_PROGRAM_RULE_UPDATE',
      'M_dhis-web-validationrule',
      'F_DATAELEMENT_PUBLIC_ADD',
      'F_RUN_VALIDATION',
      'F_OPTIONGROUP_PRIVATE_ADD',
      'F_CATEGORY_OPTION_GROUP_DELETE',
      'F_IMPORT_DATA',
      'F_PROGRAMSTAGE_ADD',
      'F_MINMAX_DATAELEMENT_DELETE',
      'F_ATTRIBUTE_DELETE',
      'F_OPTIONSET_DELETE',
      'M_dhis-web-dashboard',
      'M_dhis-web-data-administration',
      'F_ACCEPT_DATA_LOWER_LEVELS',
      'F_PROGRAM_TRACKED_ENTITY_ATTRIBUTE_GROUP_DELETE',
      'F_OPTIONGROUPSET_PUBLIC_ADD',
      'F_PROGRAM_INDICATOR_GROUP_PUBLIC_ADD',
      'F_CATEGORY_DELETE',
      'M_Scorecard_241beta5',
      'F_COLOR_SET_DELETE',
      'F_INDICATORTYPE_DELETE',
      'F_INDICATORGROUP_PRIVATE_ADD',
      'F_FRED_DELETE',
      'F_VALIDATIONCRITERIA_DELETE',
    ],
  };
  const dashboardAccess = getDashboardAccess(dashboard, user);
  it('should enable read access', () => {
    expect(dashboardAccess.read).toBeTruthy();
  });
  it('should enable write access', () => {
    expect(dashboardAccess.write).toBeTruthy();
  });
  it('should enable update access', () => {
    expect(dashboardAccess.update).toBeTruthy();
  });
  it('should enable delete access', () => {
    expect(dashboardAccess.delete).toBeTruthy();
  });
  it('should enable manage sharing access', () => {
    expect(dashboardAccess.manageSharing).toBeTruthy();
  });
});
