export enum OrgUnitTypes {
  ORGANISATION_UNIT_LEVEL = "ORGANISATION_UNIT_LEVEL",
  ORGANISATION_UNIT_GROUP = "ORGANISATION_UNIT_GROUP",
  USER_ORGANISATION_UNIT = "USER_ORGANISATION_UNIT",
  ORGANISATION_UNIT = "ORGANISATION_UNIT",
}
